### PR TITLE
[IPCT1-679] - Replace beneficiary

### PR DESCRIPTION
**Pull request by dev-jotape**
This PR fixes [IPCT1-679] at https://impactmarket.atlassian.net/browse/IPCT1-679

## Changes
replace beneficiary registry with TheGraph data

### CODE REVIEW

**Review by obernardovieira — APPROVED** [review]

**Comment by obernardovieira** [comment]
Feel free to merge @dev-jotape

**Comment by obernardovieira** [comment]
Looks good to me, but I think you forgot to update the API v2. Am I right?

**Review by obernardovieira — CHANGES_REQUESTED** [review]
Sorry, looks good to me, but I think you forgot to update the API v2. Am I right?

**Comment by dev-jotape** [comment]
@obernardovieira the claim-location service (v2) was missing.
the others have already been changed, or when we developed we already used TheGraph

**Comment by dev-jotape** [comment]
@obernardovieira fixed

**Review by obernardovieira — APPROVED** [review]

**Pull request merged**
